name: amazon_clone_final
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  badges: ^2.0.3
  carousel_slider: ^4.2.1
  dotted_border: ^2.0.0
  file_picker: ^8.0.6
  cloudinary_public: ^0.23.1
  flutter_rating_bar: ^4.0.1
  pay: ^1.0.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json
